######################################################################
env_suite: gym
env: FFSMEnv6dof-v0

# future action forecasts
action_dim: 21
horizon_steps: 1

# observation history
obs_dim: 48
cond_steps: 1
###################################################################
defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_reflow_agent.TrainReFlowAgent
name: ${env}_pre_reflow_mlp_ta${horizon_steps}_td${denoising_steps}_seed${seed}
logdir: ${oc.env:REINFLOW_LOG_DIR}/gym/pretrain/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
train_dataset_path: ${oc.env:REINFLOW_DATA_DIR}/gym/${env}/train.npz
normalization_path: ${oc.env:REINFLOW_DATA_DIR}/gym/${env}/normalization.npz
use_d4rl_dataset: False
test_in_mujoco: True
best_reward_threshold_for_success: -0.1
# base_policy_path: /home/yh/Algo_test/ReinFlow/logs/gym/pretrain/FFSM-6dof-v0_pre_reflow_mlp_ta4_td40_seed42/2025-11-29_11-58-07_42/checkpoint/best.pt
seed: 42
device: cuda:4
sim_device: cuda:4
denoising_steps: 4
batch_size: 256
train:
  n_epochs: 1000            # Optimized from 3000
  batch_size: ${batch_size}
  learning_rate: 1e-3
  weight_decay: 1e-6
  eval_save_video: True
  video_eval_freq: 5
  video_eval_num: 1
  lr_scheduler:
    first_cycle_steps: ${train.n_epochs} # 1000
    warmup_steps: 1
    min_lr: 1e-4
  save_model_freq: 1500
  test_freq: 25
wandb:
  entity: ${oc.env:REINFLOW_WANDB_ENTITY}
  project: gym-${env}-pretrain
  run: ${now:%H-%M-%S}_${name}
  offline_mode: True
model:
  _target_: model.flow.reflow.ReFlow
  network:
    _target_: model.flow.mlp_flow.FlowMLP #model.diffusion.mlp_diffusion.DiffusionMLP
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    time_dim: 16
    mlp_dims: [512, 512, 512]
    activation_type: Mish
    out_activation_type: Identity
    use_layernorm: True
    residual_style: True
  device: ${device}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
  act_min: -1
  act_max: 1 
  obs_dim: ${obs_dim}
  max_denoising_steps: ${denoising_steps}
  seed: ${seed}
  sample_t_type: uniform # beta, logitnormal
ema:
  decay: 0.995
train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}
  max_n_episodes: -1
